### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by pr130** [CorrelAid/kbtbr#2]
We could create a pkgdown website to accompany the package. this provides a place for the function / class reference + vignettes : https://pkgdown.r-lib.org/

examples: 
- https://docs.ropensci.org/crul/articles/crul.html
- https://roxygen2.r-lib.org/articles/

**Comment by MKyhos** [comment]
Opinion: this would make sense also in an early stage of the project, as it helps us to explore our own documentation and detect flaws etc. Also, it would help to communicate among the development team :)

**Comment by mpadge** [comment]
[`usethis::use_pkgdown()`](https://usethis.r-lib.org/reference/use_pkgdown.html) + `use_pkgdown_github_pages` automates everything.

**Comment by MKyhos** [comment]
Yet unclear how exactly we implement the docs for dev / release / historic versions...
Two threads / issues to follow:
- https://github.com/r-lib/pkgdown/issues/1373
- https://discuss.ropensci.org/t/pkgdown-website-for-released-or-dev-version-of-the-package/1919/7

**Comment by mpadge** [comment]
That is still not possible "out of the box," and those who want that generally dump `pkgdown` in favour of readthedocs. If different doc versions are important, you currently have to use readthedocs and not `pkgdown`. That said, it wouldn't be too difficult to hack a solution, along the lines of PR preview function such as [here](https://github.com/ropensci/dev_guide/blob/master/.github/workflows/pr.yml) - the whole thing then has to have a separate server, which in that case is netlify (because GitHub pages are only ever a single endpoint). I'd be very interested in helping developments in that direction as a useful experiment if people wanted?

It should be pretty straightforward to generate versions for multiple specified branches, and then to insert a switcher button in a custom css as part of the `pkgdown` header. The ability to do that would be a great boost to the broader community in general :rocket:

**Comment by pr130** [comment]
@mpadge we figured out [a hacky solution](https://github.com/CorrelAid/kbtbr/blob/dev/.github/workflows/pkgdown.yaml#L56) to this (@MKyhos did the initial setup work with figuring out how to put the branch into the `_pkgdown.yml` and how to build the page into a subfolder in `docs`, and i later on dealt with git issues) .. we didn't have time to figure out how to nicely integrate this into the UI of the pkgdown site so right now we only have the links hardcoded into the [README](https://github.com/CorrelAid/kbtbr/tree/dev) at the top. 

i guess for our needs this is sufficient  (hence i'm closing the issue) although i'd be personally interested in also extending this to releases and finding a way to automatically create a dropdown menu based on what subfolders are present in `docs`. do you have any pointers on how to modify the `_pkgdown.yml` yaml in this way? would the [`yaml` package](https://github.com/viking/r-yaml) be a good starting point? or do you know about anything more pkgdown specific?
