### ISSUE TITLE
KoboClient: POST method

### ISSUE THREAD

**Issue by MKyhos** [CorrelAid/kbtbr#21]
A basic structure for the `KoboClient` class was designed, which already includes a `GET` method: `KoboClient$get()`.
Likewise, a most generic `KoboClient$post()` method should be implement. 

Thus, we would like to:

- [x] Make some research on the Kobo API (priority: `v2`)  and find a suitable and easy-to-test and to-inspect POST endpoint. Check what the expected result is on server side, and request reponse.
- [x] Build a generic `KoboClient$post()` on top of `HttpClient$post()`, which can be used via `super$post()`.
- [x] If it seems suitable, extend the method with checks etc. Might also be minimal
- [x] Write a test (linked to #19)
- [x] Document the method

**Comment by LadaRudnitckaia** [comment]
I tried three different POST requests: 

1) to upload the form
crul: status 200 and nothing happening on the website
httr: same (tried httr just to check whether the problem in crud or in general)
postman: I didn’t manage to get 201 with token - no idea why - but it worked with username and password. However, even with status 201, i don’t see this new form on the website.

2) to deploy an asset (the survey that was in "Draft" section on the website),
crul: status 404
httr: same
postman: status 200 + the survey got into “Archived” on the website instead of “Deployed”

3) to clone an asset (the survey that was in "Draft" section on the website)
crul: status 200 and nothing happening on the website
postman: 400 asset_type is required. Adding asset_type=survey doesn’t solve the problem though.

**Comment by LadaRudnitckaia** [comment]
@MKyhos found the problem: The body should be not in list but in Json format
The persisting issues:
1) deploying an asset is failing
2) uploading XLS form requires a bit more research
3) nested objects in json are also failing

We can proceed to the generic KoboClient$post()

**Comment by MKyhos** [comment]
To add on 3.: in particular when we try to create a new asset from scratch, the API documentation gives the impression that we should also be able to set a `settings` field, which is itself the mentioned (nested) json object, as in (taken from the docs):
```
   {
      "name": {string},
      "settings": {
          "description": {string},
          "sector": {string},
          "country": {string},
          "share-metadata": {boolean}
      },
      "asset_type": {string}
   }
```

However, including the `settings` field leads to a `400 Bad request`.
